config/routes.rb
Rails.application.routes.draw do
  resources :pigeons
  root :to => "pigeons#new"
  post "/pigeons/deliver" => "pigeons#deliver", :as => 'pigeon_deliver'
  get '/subregion_options' => 'pigeons#subregion_options'

end

app/models/pigeon.rb
class Pigeon

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :first_name, :last_name, :email, :country, :subregion
 
  validates_presence_of :first_name, :last_name, :email, :country, :subregion
  validates_format_of :first_name, :last_name, :with => /\A[a-zA-Z]+\z/i, :message => "should contain only letters"
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i, :message =>"should have a valid format"
  validates_confirmation_of :email

  # loop through each item in hash and assign the value to each of the attributes of the message
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end if attributes
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pigeons_controller.rb
class PigeonsController < ApplicationController


  def new
    @pigeon = Pigeon.new

  end

  def create
    @pigeon = Pigeon.new(params[:pigeon])

    if @pigeon.valid?
      session[:first_name] = @pigeon.first_name
      session[:last_name] = @pigeon.last_name
      session[:email] = @pigeon.email
      session[:country] = @pigeon.country
      session[:subregion] = @pigeon.subregion
      render :show
    else
       render :new
    end
  end

  def deliver

    PigeonMailer.send_email(session[:first_name], session[:last_name], session[:email], session[:country], session[:subregion]).deliver
    flash[:notice] = 'Message on the way!'
    redirect_to :action => :new 
  end

  def subregion_options
    render partial: 'subregion_select'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pigeon_helper.rb
module PigeonHelper
  def pigeon_error_messages!
    return "" if @pigeon.errors.empty?

    messages = @pigeon.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div id="alert alert-danger">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pigeonpostoffice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pigeons/_subregion_select.html.erb
<div id="pigeon_subregion_wrapper">
  <% parent_region ||= params[:parent_region] %>
  <% unless parent_region.nil? %>
    <% country = Carmen::Country.coded(parent_region) %>
  <% end%>

  <% if country.nil? %>
    <em>Please select a country from above</em>
  <% elsif country.subregions? %>
    <%= subregion_select(:pigeon, :subregion, parent_region) %>
  <% else %>
    <%= text_field(:pigeon, :subregion) %>
  <% end %>
</div>

app/views/pigeons/new.html.erb
<main>
  <section class="container">
    <div class="col-xs-10 col-sm-6 col-md-4 col-lg-3 col-centered">
      <%= flash[:notice] if flash[:notice] %>
      <div class="grow pic">
        <%= image_tag("logo.png", alt: "Logo") %>
      </div>

      <%= form_for @pigeon do |f| %>
        <p><% if not pigeon_error_messages!.empty? %>
          <div class="alert alert-danger" role="alert">
            <a class="panel-close close" data-dismiss="alert">×</a> 
            <%= pigeon_error_messages! %>
          </div>
        <% end %></p>

        <%= f.label :first_name, :class => "sr-only"  %><br />
        <%= f.text_field :first_name, autofocus: true, :class => "form-control", :placeholder => "First Name" %><br />

        <%= f.label :last_name, :class => "sr-only"  %><br />
        <%= f.text_field :last_name, :class => "form-control", :placeholder => "Last Name" %>  <br />

        <%= f.label :email, :class => "sr-only"  %>  <br />
        <%= f.text_field :email, :class => "form-control", :placeholder => "Email" %>  <br />

        <%= f.label :email_confirmation, :class => "sr-only"  %>  <br />
        <%= f.text_field :email_confirmation, autocomplete: "off", :class => "form-control", :placeholder => "Email confirmation" %>  <br />
        
        <%= f.label :country, :class => "control-label" %>
         <%= f.country_select :country, :class => "selectpicker", prompt: 'Please select a country'  %>

        <%= f.label :subregion, :class => "control-label" %>
        <%= render partial: 'subregion_select', locals: {parent_region: f.object.country}%><br />


        <%= button_to 'Submit', pigeon_path(:id), :class => "btn btn-primary lg"%><br />
        
      <% end %>
    </div>
  </section>
</main>

app/views/pigeons/show.html.erb
<main>
  <section class="container">
    <div class="col-xs-10 col-sm-6 col-md-4 col-lg-3 col-centered">

      <div class="grow pic">
        <%= image_tag("logo.png", alt: "Logo") %>
      </div>

      <%= form_for(@pigeon, html: { class: "form-horizontal" }) do |f| %>
        <div class="form-group">
          <%= f.label :first_name, "First Name: ", :class => "col-sm-4 control-label" %>
          <div class="col-sm-8 ">
            <p class="form-control-static"><%= session[:first_name] %></p><br />
          </div>
       </div>
        <div class="form-group">
         <%= f.label :last_name, "Last Name: ", :class => "col-sm-4 control-label"  %>
        <div class="col-sm-8 col-text-left">
          <p class="form-control-static"><%= session[:last_name] %></p><br />
        </div>
       </div>
        <div class="form-group">
        <%= f.label :email, "Email: ", :class => "col-sm-4 control-label" %>
        <div class="col-sm-8 col-text-left">
          <p class="form-control-static"><%= session[:email] %></p><br />
        </div>
        </div>
        <div class="form-group">
        <%= f.label :country, "Country: ", :class => "col-sm-4 control-label" %>
        <div class="col-sm-8 col-text-left">
          <p class="form-control-static"><%= session[:country] %></p><br />
        </div>
        </div>
        <div class="form-group">
        <%= f.label :subregion, "Subregion: ", :class => "col-sm-4 control-label" %>
        <div class="col-sm-8 col-text-left">
          <p class="form-control-static"><%= session[:subregion] %></p><br />
        </div>
        </div>
        
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="show-quote-buttons">
          <%= link_to 'Cancel', new_pigeon_path, :class => "btn btn-danger"%><br />
          <%= link_to 'Send message', pigeon_deliver_path, :class => "btn btn-primary", method: :post %><br />
        </div><br />
     <% end %>
    </div>
  </section>
</main>